#!/usr/bin/env bash
# Portable OBS Studio launcher dependency installer

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with distribution built on Ubuntu TARGET_CODENAME not ${DISTRO_CODENAME}."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

if [ -e /etc/profile.d/distrobox_profile.sh ]; then
    echo "ERROR! This script is not suitable for running in Distrobox."
    exit 1
fi

sudo apt-get -y update
