#!/usr/bin/env bash
# Provision dependencies for OBS Studio Portable Container
# PipeWire and WirePlumber installer/updater for OBS Studio Portable
# - https://pipewire-debian.github.io/pipewire-debian/

if [ "${EUID}" -ne 0 ]; then
    echo "ERROR! Please run as root."
    exit 1
fi

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with distribution built on Ubuntu TARGET_CODENAME not ${DISTRO_CODENAME}."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

if [ ! -d /tmp/obs-portable ]; then
    echo "ERROR! This script is only intended to be run while composing the OBS Studio Portable container."
    exit 1
fi

echo "deb https://ppa.launchpadcontent.net/pipewire-debian/pipewire-upstream/ubuntu TARGET_CODENAME main"      >  /etc/apt/sources.list.d/pipewire.list && \
echo "#deb-src https://ppa.launchpadcontent.net/pipewire-debian/pipewire-upstream/ubuntu TARGET_CODENAME main" >> /etc/apt/sources.list.d/pipewire.list && \
echo "deb https://ppa.launchpadcontent.net/pipewire-debian/wireplumber-upstream/ubuntu TARGET_CODENAME main"      >  /etc/apt/sources.list.d/wireplumber.list && \
echo "#deb-src https://ppa.launchpadcontent.net/pipewire-debian/wireplumber-upstream/ubuntu TARGET_CODENAME main" >> /etc/apt/sources.list.d/wireplumber.list && \
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FC43B7352BCC0EC8AF2EEB8B25088A0359807596 && \
apt-get -y update && \
DEBIAN_FRONTEND=noninteractive apt-get -y install \
	gstreamer1.0-pipewire \
	libpipewire-0.3-0 \
	libpipewire-0.3-modules\
	libspa-0.2-bluetooth \
	libspa-0.2-jack \
	libspa-0.2-modules \
	pipewire \
	pipewire-audio-client-libraries \
	pipewire-pulse \
	pipewire-bin \
	pipewire-jack \
	pipewire-alsa \
	pipewire-v4l2 \
	pipewire-libcamera \
	pipewire-locales \
	wireplumber \
	gir1.2-wp-0.4 \
	libwireplumber-0.4-0 && \
