#!/usr/bin/env bash
# Portable OBS Studio launcher dependency installer

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with distribution built on Ubuntu TARGET_CODENAME not ${DISTRO_CODENAME}."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

sudo true

PORTABLE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
if ! cmp --quiet "${PORTABLE_DIR}/lib/libndi.so" /usr/local/lib/libndi.so.5; then
    sudo mkdir -p /usr/local/lib >/dev/null 2>&1
    sudo cp "${PORTABLE_DIR}/lib/libndi.so" /usr/local/lib/libndi.so.5
fi

if [ -e /etc/profile.d/distrobox_profile.sh ]; then
    echo "deb https://ppa.launchpadcontent.net/pipewire-debian/pipewire-upstream/ubuntu TARGET_CODENAME main" | sudo tee /etc/apt/sources.list.d/pipewire-debian-ubuntu-pipewire-upstream-TARGET_CODENAME.list
    echo "#deb-src https://ppa.launchpadcontent.net/pipewire-debian/pipewire-upstream/ubuntu TARGET_CODENAME main" | sudo tee -a /etc/apt/sources.list.d/pipewire-debian-ubuntu-pipewire-upstream-TARGET_CODENAME.list
    echo "deb https://ppa.launchpadcontent.net/pipewire-debian/wireplumber-upstream/ubuntu TARGET_CODENAME main" | sudo tee /etc/apt/sources.list.d/pipewire-debian-ubuntu-wireplumber-upstream-TARGET_CODENAME.list
    echo "#deb-src https://ppa.launchpadcontent.net/pipewire-debian/wireplumber-upstream/ubuntu TARGET_CODENAME main" | sudo tee -a /etc/apt/sources.list.d/pipewire-debian-ubuntu-wireplumber-upstream-TARGET_CODENAME.list
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FC43B7352BCC0EC8AF2EEB8B25088A0359807596
    sudo apt-get -y update
    sudo apt-get -y --no-install-recommends install \
        gstreamer1.0-pipewire \
        libpipewire-0.3-0 \
        libpipewire-0.3-modules\
        libspa-0.2-bluetooth \
        libspa-0.2-jack \
        libspa-0.2-modules \
        pipewire \
        pipewire-audio-client-libraries \
        pipewire-pulse \
        pipewire-bin \
        pipewire-jack \
        pipewire-alsa \
        pipewire-v4l2 \
        pipewire-libcamera \
        gir1.2-wp-0.4 \
        libwireplumber-0.4-0 \
        mesa-vdpau-drivers \
        mesa-va-drivers
else
    sudo apt-get -y update
    sudo apt-get -y --no-install-recommends install v4l2loopback-dkms v4l2loopback-utils
fi
