#!/usr/bin/env bash
# Portable OBS Studio launcher

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with distribution built on Ubuntu TARGET_CODENAME not ${DISTRO_CODENAME}."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

PORTABLE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

if [ ! -d "${PORTABLE_DIR}/bin/64bit" ]; then
    echo "ERROR! Could not find ${PORTABLE_DIR}/bin/64bit."
    exit 1
fi

# If running in an OBS Studio Portable container, run the config fix script
if [ -x /etc/profile.d/99-obs-config-fix.sh ]; then
    /etc/profile.d/99-obs-config-fix.sh
fi

# If running in a Distrobox container, set up the environment to use the container's libraries
if [ -e /etc/profile.d/distrobox_profile.sh ]; then
    # Override the GIO modules path
    export GIO_EXTRA_MODULES="/usr/lib/x86_64-linux-gnu/gio/modules/"

    # Override GStreamer paths
    export GST_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
    export GST_PLUGIN_SYSTEM_PATH="/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
    export GST_PLUGIN_SYSTEM_PATH_1_0="/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
    export GST_PLUGIN_SCANNER="/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"

    # Make sure Qt finds plugins from the container, not the host.
    if [ "${DISTRO_CODENAME}" == "focal" ]; then
        export QT_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/qt5/plugins"
    else
        export QT_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/qt6/plugins"
    fi
    export QT_QPA_PLATFORMTHEME=""
    export QT_STYLE_OVERRIDE=""
    export LD_LIBRARY_PATH="${PORTABLE_DIR}/bin/64bit":"${PORTABLE_DIR}/obs-plugins/64bit":"${PORTABLE_DIR}/data/obs-scripting/64bit":"${PORTABLE_DIR}/cef":"${PORTABLE_DIR}/lib"
else
    export LD_LIBRARY_PATH="${PORTABLE_DIR}/bin/64bit":"${PORTABLE_DIR}/obs-plugins/64bit":"${PORTABLE_DIR}/data/obs-scripting/64bit":"${PORTABLE_DIR}/cef":"${PORTABLE_DIR}/lib"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi

# Purge the GPU cache to avoid issues with the host's GPU drivers
if [ -e "${PORTABLE_DIR}/config/obs-studio/plugin_config/obs-browser/GPUCache/index" ]; then
    rm -f "${PORTABLE_DIR}"/config/obs-studio/plugin_config/obs-browser/GPUCache/*
fi

cd "${PORTABLE_DIR}/bin/64bit" || exit 1
exec ./obs --portable "${@}"
