#!/usr/bin/env bash
# Portable OBS Studio launcher

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with distribution built on Ubuntu TARGET_CODENAME not ${DISTRO_CODENAME}."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

PORTABLE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
export LD_LIBRARY_PATH="${PORTABLE_DIR}/bin/64bit":"${PORTABLE_DIR}/obs-plugins/64bit":"${PORTABLE_DIR}/data/obs-scripting/64bit":"${PORTABLE_DIR}/cef":"${PORTABLE_DIR}/lib"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

if [ ! -d "${PORTABLE_DIR}/bin/64bit" ]; then
    echo "ERROR! Could not find ${PORTABLE_DIR}/bin/64bit."
    exit 1
fi

# If we're in an OBS Studio Portable container, run the config fix script
if [ -x /etc/profile.d/99-obs-config-fix.sh ]; then
  /etc/profile.d/99-obs-config-fix.sh
  # Make sure gstream find plugins from the container, not the host.
  export GST_PLUGIN_SYSTEM_PATH_1_0=/usr/lib/x86_64-linux-gnu/gstreamer-1.0:"${GST_PLUGIN_SYSTEM_PATH_1_0}"
fi

cd "${PORTABLE_DIR}/bin/64bit"
exec ./obs --portable "${@}"
