#!/usr/bin/env bash
# Portable OBS Studio gamecapture launcher
# https://github.com/nowrep/obs-vkcapture

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    DISTRO_VERSION=$(grep VERSION_ID /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with Ubuntu TARGET_VERSION (TARGET_CODENAME), not ${DISTRO_VERSION} (${DISTRO_CODENAME})."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

if [ "$#" -eq 0 ]; then
    echo "ERROR: No program supplied"
    echo
    echo "Usage: $(basename "${0}") <program>"
    exit 1
fi

PORTABLE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

export LD_LIBRARY_PATH="${PORTABLE_DIR}/lib"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export LD_PRELOAD="${PORTABLE_DIR}/lib/libobs_glcapture.so"${LD_PRELOAD:+:$LD_PRELOAD}
export OBS_VKCAPTURE=1

# Cannot create EGLImage: Arguments are inconsistent
#   If you get this error with Vulkan capture, try starting the game with the
#   following uncommented:
#export OBS_VKCAPTURE_LINEAR=1

exec "${@}"
